name: tekartik_platform_context_example
version: 0.1.0
description: Example for platform context
dependencies:
  platform_context:
    git: https://github.com/alextekartik/platform_context.dart
  browser: any
  bootstrap: any
  dart_to_js_script_rewriter: any
dev_dependencies:
  test: any
  dev_test: any
transformers:
- dart_to_js_script_rewriter
